services:
  backend:
    image: dishu-backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - dishu-network

  frontend:
    image: dishu-frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    networks:
      - dishu-network

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: dishu_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootPassword123
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - dishu-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: rootPassword123
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - dishu-network

volumes:
  db_data:

networks:
  dishu-network:
