version: "3.8"

services:
  frontend:
    image: immo-agency-frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    networks:
      - immo-network

networks:
  immo-network:
